name: Feature request
description: Something jevtest should do
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: What do you need to test that you can't today?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How you'd like to write it in a test file
      render: yaml
